# Generated by Django 4.1.5 on 2023-03-23 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=100)),
                ('manure_applied', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('slope_dem', models.FloatField(blank=True, default=1.0, null=True)),
                ('man_appllast_season', models.CharField(default=' ', max_length=100)),
                ('man_appl_2_season', models.CharField(default=' ', max_length=100)),
                ('man_appl_3_season', models.CharField(default=' ', max_length=100)),
                ('man_appl_4_season', models.CharField(default=' ', max_length=100)),
                ('man_appl_5_season', models.CharField(default=' ', max_length=100)),
                ('man_frequency', models.FloatField(blank=True, default=1.0, null=True)),
                ('plant_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('land_form', models.CharField(default=' ', max_length=100)),
                ('slope', models.CharField(default=' ', max_length=100)),
                ('slope_position', models.CharField(default=' ', max_length=100)),
                ('wi', models.FloatField(blank=True, default=1.0, null=True)),
                ('tpi', models.FloatField(blank=True, default=1.0, null=True)),
                ('wealth_class', models.CharField(default=' ', max_length=100)),
                ('farmer_practice', models.FloatField(null=True)),
                ('fertilizer_practice', models.FloatField(null=True)),
                ('yield_difference', models.FloatField(null=True)),
                ('prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('predicted_practice', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(upload_to='')),
            ],
        ),
    ]
